name: Auto Check-In

on:
  schedule:
    - cron: '35 5 * * *'   # 每天北京时间13:08签到（UTC 05:08）
  workflow_dispatch:        # 可手动触发测试

jobs:
  check_in_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "当前北京时间: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          echo "安装依赖中..."
          pip install -r requirements.txt

      - name: Run Check-In Script
        run: |
          echo "开始执行签到脚本..."
          python check_in.py
