name: Auto Check-In

on:
  schedule:
    - cron: '50 4 * * *'  # 每天北京时间12:50执行签到（UTC 04:50）
  workflow_dispatch:

jobs:
  check_in_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run check-in script
        run: python check_in.py
